# Generated by Django 5.1.1 on 2024-09-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='horarios_funcionamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='lugares_pagos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='monitoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
