# Generated by Django 5.1.1 on 2024-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0002_pontoturistico_horarios_funcionamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='lugares_pagos',
            field=models.CharField(max_length=50),
        ),
    ]
