# Generated by Django 5.1.1 on 2024-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0003_alter_pontoturistico_lugares_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='horarios_funcionamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='monitoria',
            field=models.BooleanField(default=False),
        ),
    ]
