# Generated by Django 5.1.1 on 2024-09-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0004_alter_pontoturistico_horarios_funcionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='descricao',
        ),
    ]
