# Generated by Django 5.1.1 on 2024-09-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0006_alter_pontoturistico_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
    ]
