# Generated by Django 5.1.1 on 2024-09-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0007_alter_pontoturistico_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
