# Generated by Django 5.1.1 on 2024-09-12 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0008_alter_pontoturistico_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verotur_App.categorias'),
        ),
    ]
