# Generated by Django 5.1.1 on 2024-09-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='place_id',
        ),
    ]
