# Generated by Django 5.1.1 on 2024-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0002_alter_pontoturistico_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
