# Generated by Django 5.1.1 on 2024-09-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0003_pontoturistico_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='place_id',
        ),
    ]
