# Generated by Django 5.1.1 on 2024-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0004_remove_pontoturistico_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='place_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
