# Generated by Django 5.1.1 on 2024-09-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0006_alter_pontoturistico_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCategorias',
            fields=[
                ('idtb_categorias', models.AutoField(db_column='idtb_Categorias', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tb_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbPontosTuristicos',
            fields=[
                ('idtable1', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('nome', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('horarios_fechamento', models.CharField(max_length=45)),
                ('lugares_pagos', models.CharField(max_length=45)),
                ('monitoria', models.CharField(max_length=45)),
                ('table1col', models.CharField(max_length=45)),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tb_pontos_turisticos',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='PontoTuristico',
        ),
    ]
