# Generated by Django 5.1.1 on 2024-09-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0007_tbcategorias_tbpontosturisticos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbcategorias',
            options={'managed': False, 'verbose_name': 'TbCategoria', 'verbose_name_plural': 'TbCategorias'},
        ),
        migrations.AlterModelOptions(
            name='tbpontosturisticos',
            options={'managed': False, 'verbose_name': 'TbPontosTuristico', 'verbose_name_plural': 'TbPontosTuristicos'},
        ),
    ]
