# Generated by Django 5.1.1 on 2024-09-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0008_alter_tbcategorias_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id_ponto_turistico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('endereco', models.CharField(max_length=100)),
                ('horarios_funcionamento', models.CharField(max_length=45)),
                ('lugares_pagos', models.CharField(max_length=45)),
                ('monitoria', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('latitude', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ponto_turistico',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TbCategorias',
        ),
        migrations.DeleteModel(
            name='TbPontosTuristicos',
        ),
    ]
