# Generated by Django 5.1.1 on 2024-09-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0010_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuseruserpermissions',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
    ]
