# Generated by Django 5.1.1 on 2024-10-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verotur_App', '0011_alter_authuseruserpermissions_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categorias', models.AutoField(db_column='ID_categorias', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontosTuristicos',
            fields=[
                ('id_pontos_turisticos', models.AutoField(db_column='ID_pontos_turisticos', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('imagem', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=45)),
                ('horarios_funcionamento', models.CharField(max_length=45)),
                ('lugares_pagos', models.CharField(max_length=45)),
                ('monitoria', models.CharField(max_length=45)),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('categorias_id_categorias', models.ForeignKey(db_column='categorias_ID_categorias', on_delete=django.db.models.deletion.DO_NOTHING, to='verotur_App.categorias')),
            ],
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='PontoTuristico',
        ),
    ]
