# Generated by Django 5.1.2 on 2024-10-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='descricao',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='imagem',
            field=models.ImageField(upload_to='pontos_turisticos/'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='latitude',
            field=models.FloatField(max_length=45),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='longitude',
            field=models.FloatField(max_length=45),
        ),
    ]
