# Generated by Django 5.1.2 on 2024-10-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0003_alter_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='nome_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='categorias',
            name='nome_es',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='categorias',
            name='nome_pt_br',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='descricao_en',
            field=models.TextField(max_length=2500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='descricao_es',
            field=models.TextField(max_length=2500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='descricao_pt_br',
            field=models.TextField(max_length=2500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='endereco_en',
            field=models.CharField(max_length=75, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='endereco_es',
            field=models.CharField(max_length=75, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='endereco_pt_br',
            field=models.CharField(max_length=75, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='horarios_funcionamento_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Horários de Funcionamento'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='horarios_funcionamento_es',
            field=models.CharField(max_length=45, null=True, verbose_name='Horários de Funcionamento'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='horarios_funcionamento_pt_br',
            field=models.CharField(max_length=45, null=True, verbose_name='Horários de Funcionamento'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='lugares_pagos_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Lugares Pagos'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='lugares_pagos_es',
            field=models.CharField(max_length=45, null=True, verbose_name='Lugares Pagos'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='lugares_pagos_pt_br',
            field=models.CharField(max_length=45, null=True, verbose_name='Lugares Pagos'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='monitoria_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Monitoria'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='monitoria_es',
            field=models.CharField(max_length=45, null=True, verbose_name='Monitoria'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='monitoria_pt_br',
            field=models.CharField(max_length=45, null=True, verbose_name='Monitoria'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='nome_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='nome_es',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='nome_pt_br',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=45, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='categorias_id_categorias',
            field=models.ForeignKey(db_column='categorias_ID_categorias', on_delete=django.db.models.deletion.DO_NOTHING, to='veroturApp.categorias', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='descricao',
            field=models.TextField(max_length=2500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='endereco',
            field=models.CharField(max_length=75, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='horarios_funcionamento',
            field=models.CharField(max_length=45, verbose_name='Horários de Funcionamento'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='imagem',
            field=models.ImageField(upload_to='pontos_turisticos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='lugares_pagos',
            field=models.CharField(max_length=45, verbose_name='Lugares Pagos'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='monitoria',
            field=models.CharField(max_length=45, verbose_name='Monitoria'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='nome',
            field=models.CharField(max_length=45, verbose_name='Nome'),
        ),
    ]
