# Generated by Django 5.1.2 on 2024-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0004_categorias_nome_en_categorias_nome_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='imagem',
            field=models.ImageField(upload_to='pontos_turisticos/'),
        ),
    ]
