# Generated by Django 5.1.2 on 2024-10-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0006_categorias_slug_alter_categorias_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
