# Generated by Django 5.1.2 on 2024-10-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0007_alter_categorias_nome_alter_categorias_nome_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='slug'),
        ),
    ]
