# Generated by Django 5.1.2 on 2024-10-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0008_alter_categorias_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='pontosturisticos',
            options={'verbose_name': 'Ponto Turístico', 'verbose_name_plural': 'Pontos Turísticos'},
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='imagem',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='nome_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='nome_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='nome_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
