# Generated by Django 5.1.2 on 2024-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0009_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='imagem',
            field=models.ImageField(upload_to='media/pontos_turisticos/pontos_turisticos/'),
        ),
    ]
