# Generated by Django 5.1.2 on 2024-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0012_alter_pontosturisticos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='lugares_pagos',
            field=models.CharField(max_length=100, verbose_name='Lugares Pagos'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='lugares_pagos_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Lugares Pagos'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='lugares_pagos_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Lugares Pagos'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='lugares_pagos_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Lugares Pagos'),
        ),
    ]
