# Generated by Django 5.1.2 on 2024-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0014_alter_pontosturisticos_horarios_funcionamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.TextField(max_length=2500, verbose_name='Descrição')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Senac',
            },
        ),
    ]
