# Generated by Django 5.1.2 on 2024-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veroturApp', '0015_senac'),
    ]

    operations = [
        migrations.AddField(
            model_name='senac',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='senac',
            name='descricao',
            field=models.TextField(max_length=2000, verbose_name='Descrição'),
        ),
    ]
