# Generated by Django 5.1.2 on 2024-10-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PontosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('imagem', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=45)),
                ('horarios_funcionamento', models.CharField(max_length=45)),
                ('lugares_pagos', models.CharField(max_length=45)),
                ('monitoria', models.CharField(max_length=45)),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('categorias_id_categorias', models.ForeignKey(db_column='categorias_ID_categorias', on_delete=django.db.models.deletion.DO_NOTHING, to='veroturApp.categorias')),
            ],
        ),
    ]
